# # Build Options

WPM_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
# RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_LED_COUNT = 64
#define RGBLIGHT_SLEEP



#define OLEDDISPLAY_TIMEOUT 10
#define OLED_BRIGHTNESS 120
#define RGBLIGHT_TIMEOUT 15  // in Minutes
#define DEBOUNCE 1
#define USB_MAX_POWER_CONSUMPTION 500
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_LED_COUNT 64
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200

#define EE_HANDS
#define MASTER_LEFT
#define MASTER_RIGHT
